---
# defaults file for wpasupplicant
wpasupplicant__pkg_name_d: 'wpasupplicant'
wpasupplicant__pkg_name_c: 'wpa_supplicant'
wpasupplicant__pkg_update_cache: 'yes'
wpasupplicant__conf_dir: '/etc/wpa_supplicant'

wpasupplicant__service: 'wpa_supplicant'
wpasupplicant__enabled: True
wpasupplicant__state: started

wpasupplicant__identity: "inverse"
wpasupplicant__password:  "secret"

wpasupplicant__configs:
  - name: 'eap_tls'
    dir: '{{ wpasupplicant__conf_dir }}/eap_tls'
    filename: 'eap_tls.conf'
    ctrl_interface_group: 0
    eapol_version: 2
    ap_scan: 0
    key_mgmt: 'IEEE8021X'
    eap: 'TLS'
    ca_cert: "{{ wpasupplicant__conf_dir }}/eap_tls/ca.pem"
    client_cert: "{{ wpasupplicant__conf_dir }}/eap_tls/client.pem"
    private_key: "{{ wpasupplicant__conf_dir }}/eap_tls/client.key"
    private_key_passwd: 'whatever'
    eapol_flags: 3

  - name: 'eap_peap_mschapv2'
    dir: '{{ wpasupplicant__conf_dir }}/eap_peap'
    filename: 'eap_peap_mschapv2.conf'
    ctrl_interface_group: 0
    eapol_version: 2
    ap_scan: 0
    key_mgmt: 'IEEE8021X'
    eap: 'PEAP'
    identity: '{{ wpasupplicant__identity }}'
    password: '{{ wpasupplicant__password }}'
    phase2: "autheap: MSCHAPV2"
    eapol_flags: 3

  - name: 'wireless_open'
    dir: '{{ wpasupplicant__conf_dir }}/wireless_open'
    filename: 'wireless_open.conf'
    ssid: 'PF-Open'
    key_mgmt: 'NONE'
    priority: '100'

  - name: 'wireless_secure'
    dir: '{{ wpasupplicant__conf_dir }}/wireless_secure'
    filename: 'wireless_secure.conf'
    ssid: 'PF-Secure'
    key_mgmt: 'WPA-EAP'
    eap: 'PEAP'
    phase2: 'NONE'
    identity: '{{ wpasupplicant__identity }}'
    password: '{{ wpasupplicant__password }}'

configs_available_values:
  ctrl_interface: '' # default('/var/run/wpasupplicant')
  ctrl_interface_group: ''
  eapol_version: ''
  ap_scan: ''
  ssid: ''
  key_mgmt: ''
  priority: ''
  ca_cert: ''
  client_cert: ''
  private_key: ''
  private_key_passwd: ''
  eapol_flags: ''
  eap: ''
  phase2: ''
  identity: ''
  password: ''
