---
# handlers file for hostapd
- name: net pending
  command: net pending
  become: true
  listen: apply changes

- name: net commit
  command: net commit
  become: true
  listen: apply changes

- name: restart hostapd
  service:
    name: hostapd.service
    state: restarted
...
